<?php

/**
 * Tests for the Webhook service
 *
 * @license MIT
 * @copyright 2025 CloudContactAI LLC
 */

declare(strict_types=1);

namespace CloudContactAI\CCAI\Tests\Webhook;

use CloudContactAI\CCAI\CCAI;
use CloudContactAI\CCAI\Webhook\Webhook;
use Mockery;
use PHPUnit\Framework\TestCase;
use RuntimeException;

class WebhookTest extends TestCase
{
    /**
     * @var CCAI Mock CCAI client
     */
    private $ccai;

    /**
     * @var Webhook Webhook service instance
     */
    private Webhook $webhook;

    protected function setUp(): void
    {
        $this->ccai = Mockery::mock(CCAI::class);
        $this->ccai->shouldReceive('getClientId')->andReturn('test-client-id');
        $this->webhook = new Webhook($this->ccai);
    }

    protected function tearDown(): void
    {
        Mockery::close();
    }

    /**
     * Test registering a webhook with auto-generated secret
     */
    public function testRegisterAutoGeneratedSecret(): void
    {
        $config = [
            'url' => 'https://myapp.com/webhook',
            // secretKey not provided - server should auto-generate
        ];

        $this->ccai->shouldReceive('request')
            ->once()
            ->with(
                'POST',
                '/v1/client/test-client-id/integration',
                [[
                    'url'             => 'https://myapp.com/webhook',
                    'method'          => 'POST',
                    'integrationType' => 'ALL',
                ]]
            )
            ->andReturn([['id' => 1, 'url' => 'https://myapp.com/webhook', 'method' => 'POST', 'integrationType' => 'ALL', 'secretKey' => 'sk_live_auto_generated']]);

        $response = $this->webhook->register($config);

        $this->assertEquals(1, $response['id']);
        $this->assertEquals('https://myapp.com/webhook', $response['url']);
        $this->assertEquals('sk_live_auto_generated', $response['secretKey']);
    }

    /**
     * Test registering a webhook with a custom secret
     */
    public function testRegisterCustomSecret(): void
    {
        $config = [
            'url'       => 'https://myapp.com/webhook',
            'secretKey' => 'my-custom-secret',
        ];

        $this->ccai->shouldReceive('request')
            ->once()
            ->with(
                'POST',
                '/v1/client/test-client-id/integration',
                [[
                    'url'             => 'https://myapp.com/webhook',
                    'method'          => 'POST',
                    'integrationType' => 'ALL',
                    'secretKey'       => 'my-custom-secret',
                ]]
            )
            ->andReturn([['id' => 1, 'url' => 'https://myapp.com/webhook', 'method' => 'POST', 'integrationType' => 'ALL', 'secretKey' => 'my-custom-secret']]);

        $response = $this->webhook->register($config);

        $this->assertEquals(1, $response['id']);
        $this->assertEquals('https://myapp.com/webhook', $response['url']);
        $this->assertEquals('my-custom-secret', $response['secretKey']);
    }

    /**
     * Test updating a webhook
     */
    public function testUpdate(): void
    {
        $config = ['url' => 'https://myapp.com/webhook-v2'];

        $this->ccai->shouldReceive('request')
            ->once()
            ->with(
                'POST',
                '/v1/client/test-client-id/integration',
                [[
                    'id'              => 1,
                    'url'             => 'https://myapp.com/webhook-v2',
                    'method'          => 'POST',
                    'integrationType' => 'ALL',
                ]]
            )
            ->andReturn([['id' => 1, 'url' => 'https://myapp.com/webhook-v2', 'method' => 'POST', 'integrationType' => 'ALL']]);

        $response = $this->webhook->update('1', $config);

        $this->assertEquals(1, $response['id']);
        $this->assertEquals('https://myapp.com/webhook-v2', $response['url']);
    }

    /**
     * Test listing all webhooks
     */
    public function testList(): void
    {
        $this->ccai->shouldReceive('request')
            ->once()
            ->with('GET', '/v1/client/test-client-id/integration')
            ->andReturn([
                ['id' => 1, 'url' => 'https://myapp.com/webhook'],
                ['id' => 2, 'url' => 'https://myapp.com/other'],
            ]);

        $response = $this->webhook->list();

        $this->assertCount(2, $response);
        $this->assertEquals(1, $response[0]['id']);
        $this->assertEquals(2, $response[1]['id']);
    }

    /**
     * Test deleting a webhook
     */
    public function testDelete(): void
    {
        $this->ccai->shouldReceive('request')
            ->once()
            ->with('DELETE', '/v1/client/test-client-id/integration/1')
            ->andReturn(['success' => true, 'message' => 'Webhook deleted']);

        $response = $this->webhook->delete('1');

        $this->assertTrue($response['success']);
    }

    /**
     * Test verifySignature with a valid signature
     */
    public function testVerifySignatureValid(): void
    {
        $clientId = 'test-client-id';
        $eventHash = 'event-hash-abc123';
        $secret = 'mysecret';

        // Compute expected signature: HMAC-SHA256(secretKey, clientId:eventHash) in Base64
        $data = "{$clientId}:{$eventHash}";
        $computed = hash_hmac('sha256', $data, $secret, true); // raw binary output
        $expected = base64_encode($computed);

        $this->assertTrue($this->webhook->verifySignature($expected, $clientId, $eventHash, $secret));
    }

    /**
     * Test verifySignature with an invalid signature
     */
    public function testVerifySignatureInvalid(): void
    {
        $this->assertFalse(
            $this->webhook->verifySignature('invalidsignature', 'client-id', 'event-hash', 'mysecret')
        );
    }

    /**
     * Test parsing a valid webhook payload
     */
    public function testParseWebhookEvent(): void
    {
        $payload = '{"event":"MESSAGE_SENT","id":"msg-456","phone":"+15551234567"}';

        $event = $this->webhook->parseWebhookEvent($payload);

        $this->assertEquals('MESSAGE_SENT', $event['event']);
        $this->assertEquals('msg-456', $event['id']);
        $this->assertEquals('+15551234567', $event['phone']);
    }

    /**
     * Test parsing an invalid JSON payload throws an exception
     */
    public function testParseWebhookEventInvalidJson(): void
    {
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Invalid JSON payload');

        $this->webhook->parseWebhookEvent('not-valid-json');
    }
}
